[package]
name = "cls-capp-pwgen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
rand = "0.8.5"
cli-clipboard = "0.4"
log = "0.4.28"
simple_logger = "5.0.0"

[[bin]]
name = "cls-capp-pwgen"
path = "src/main.rs"