name: Release Rust Binary

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.1)'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call build workflow
        uses: ./.github/actions/rust-ubuntu

      - name: Download binary from called workflow
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.build_binary.outputs.artifact_name }}
          path: ./

      - name: Set up Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create tag
        id: create_tag
        run: |
          TAG="${{ github.event.inputs.tag }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Failing."
            exit 1
          fi
          git tag "$TAG"
          git push origin "$TAG"
          echo "::set-output name=tag::$TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          files: pwgen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}